// packages/mod-handover-spa/src/app/mod-handovers/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component( {
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: [ './home.component.scss' ]
} )
export class HomeComponent implements OnInit {
  currentDate: Date = new Date();
  datePickerConfig: any = {
    openOnClick: true
  };

  constructor () { }

  ngOnInit (): void {

  }

}

<section class="block pf-u-mt-4xl">

  <div class="pf-l-grid pf-m-gutter">
    <div class="pf-l-grid__item pf-m-4-col">
      <div class="pf-c-card" id="card-action-example-3">
        <div class="pf-c-card__header">
          <div class="pf-c-card__actions">
            <div class="count-number">
              1727
            </div>
          </div>
        </div>
        <div class="pf-c-card__body" id="card-action-example-3-check-label">Handovers of 2020
          <div class="pf-c-progress pf-m-sm" id="progress-sm-example">
            <div class="pf-c-progress__bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="33"
              aria-describedby="progress-sm-example-description">
              <div class="pf-c-progress__indicator" style="width:33%;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pf-l-grid__item pf-m-4-col">
      <div class="pf-c-card" id="card-action-example-3">
        <div class="pf-c-card__header">
          <div class="pf-c-card__actions">
            <div class="count-number">
              10
            </div>
          </div>
        </div>
        <div class="pf-c-card__body" id="card-action-example-3-check-label">Platform
          <div class="pf-c-progress pf-m-sm" id="progress-sm-example">
            <div class="pf-c-progress__bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="33"
              aria-describedby="progress-sm-example-description">
              <div class="pf-c-progress__indicator" style="width:33%;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pf-l-grid__item pf-m-4-col">
      <div class="pf-c-card" id="card-action-example-3">
        <div class="pf-c-card__header">
          <div class="pf-c-card__actions">
            <div class="count-number">
              7
            </div>
          </div>
        </div>
        <div class="pf-c-card__body" id="card-action-example-3-check-label">
          Total Handovers
          <div class="pf-c-progress pf-m-sm" id="progress-sm-example">
            <div class="pf-c-progress__bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="33"
              aria-describedby="progress-sm-example-description">
              <div class="pf-c-progress__indicator" style="width:33%;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="pf-l-grid pf-m-gutter pf-u-mt-3xl">
    <div class="pf-l-grid__item pf-m-8-col">
      <div class="pf-c-tabs" id="tabbed">
        <button class="pf-c-tabs__scroll-button" disabled aria-hidden="true" aria-label="Scroll left">
          <i class="fas fa-angle-left" aria-hidden="true"></i>
        </button>
        <ul class="pf-c-tabs__list">
          <li class="pf-c-tabs__item pf-m-current">
            <button class="pf-c-tabs__link" id="tabbed-platform-link">
              <span class="pf-c-tabs__item-text">Platform</span>
            </button>
          </li>
          <li class="pf-c-tabs__item">
            <button class="pf-c-tabs__link" id="tabbed-ecs-link">
              <span class="pf-c-tabs__item-text">ECS</span>
            </button>
          </li>
          <li class="pf-c-tabs__item">
            <button class="pf-c-tabs__link" id="tabbed-aps-link">
              <span class="pf-c-tabs__item-text">APS</span>
            </button>
          </li>
        </ul>
        <button class="pf-c-tabs__scroll-button" disabled aria-hidden="true" aria-label="Scroll right">
          <i class="fas fa-angle-right" aria-hidden="true"></i>
        </button>
      </div>
    </div>
    <div class="pf-l-grid__item pf-m-2-col">
      <div class="pf-c-input-group">
        <input class="pf-c-form-control" type="date" id="textInput9" name="textInput9"
          aria-label="Date input example" />
      </div>
    </div>
    <div class="pf-l-grid__item pf-m-1-col">
      <button class="pf-c-button pf-m-primary" type="button" routerLink="new">Create Handover</button>
    </div>
  </div>
  <div class="pf-l-grid pf-m-gutter pf-u-mt-lg">
    <div class="pf-l-grid__item pf-m-6-col">
      <div class="pf-c-card pf-m-hoverable pf-m-compact" id="card-1">
        <div class="pf-c-card__title">
          <p id="card-1-check-label">Summary</p>
        </div>
        <div class="pf-c-card__body">
          <p class="stat-name">Manager Name: <span>Hi</span></p>
          <p class="stat-name">Handover Date: <span>Jun 19, 2020</span></p>
        </div>
        <div class="pf-c-card__body">
          <p class="stat-name">Handover Statistics</p>
          <div class="pf-l-grid pf-m-gutter">
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">FTS: <span>188</span></p>
            </div>
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">ACE: <span>0</span></p>
            </div>
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">RME: <span>1</span></p>
            </div>
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">Unassigned: <span>26</span></p>
            </div>
          </div>

          <div class="pf-l-grid pf-m-gutter">
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">WoRH: <span>188</span></p>
            </div>
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">WoC: <span>154</span></p>
            </div>
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">Unassigned NCQ: <span>13</span></p>
            </div>
            <div class="pf-l-grid__item pf-m-3-col">
              <p class="stat-name">Urgent Breaches: <span>13</span></p>
            </div>
          </div>
        </div>
        <div class="pf-c-card__body">
          <p class="stat-name">Handover Statistics</p>
          <p>13</p>


        </div>
      </div>
    </div>
  </div>
</section>

// packages/feedback-spa/src/views/Home.vue
<template>
  <div class="home pf-u-mt-4xl">
    <div class="pf-l-grid pf-m-gutter">
      <div class="pf-l-grid__item pf-m-4-col">
        <div class="pf-c-card" id="card-action">
          <div class="pf-c-card__header">
            <div class="pf-c-card__actions">
              <div class="count-number">
                10
              </div>
            </div>
          </div>
          <div class="pf-c-card__body" id="card-action-check-label">All
            <div class="pf-c-progress pf-m-sm" id="progress-sm-example">
              <div class="pf-c-progress__bar" role="progressbar" aria-valuemin="0" aria-valuemax="100"
                aria-valuenow="100" aria-describedby="progress-sm-example-description">
                <div class="pf-c-progress__indicator" style="width:100%"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>

export default {
  name: 'Feedback',
  data () {
    return {
      issueStats: []
    }
  }
}
</script>

<style scoped>
.count-number {
  color: #4285f4;
  font-weight: 100;
  font-size: 35px;
}
</style>
